### ISSUE TITLE
How many imports can you have?

### ISSUE THREAD

**Issue by Mearsheimer** [Montana/travis-build-import#1]
Hi @Montana, 

Your `.travis.yml` reads:

```yaml
language: ruby

script: echo "Montana testing the Build Import feature"

import:
  - ./.travis/all-the-rubies.yml
  - ./.travis/only-some-branches.yml

install: skip
```
I see there's two imports, is there a soft limit on how many imports you can have?

**Comment by Montana** [comment]
Hello,

For future reference, consider posting questions like this on the [community forums](travis-ci.community). That way, everyone can benefit from my answers. You can import as many configurations as you need - there's no set limit per se. 

The number of imports that will work smoothly does depend on a myriad of factors, however. This includes how many concurrent jobs your account allows, your virtual machine's size, and other factors. 

For example, I have a private repository with a `.travis.yml` that looks like this: 

```yaml
before_install:
  - export MAVEN_OPTS="-Xms512m -Xmx3g -XX:PermSize=256m $MAVEN_OPTS"
  
import: 
  - src/test/resources/docker/build.yml
  - src/test/resources/docker/run.yml
  - src/test/resources/docker/config.yml
  - src/test/resources/docker/quay.yml
  - src/test/resources/docker/openshift.yml
  - src/test/resources/docker/kubernetes.yml

script:
  - mvn clean verify sonar:
  - ./src/test/resources/docker/metrics.sh
```

Thank you,
-Michael Mendy
